# Generated by Django 2.1.1 on 2019-01-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=50)),
                ('etat', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('lieu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement_name', models.CharField(max_length=50)),
                ('disponibility', models.CharField(max_length=50)),
            ],
        ),
    ]
